### ISSUE TITLE
AttributeError: 'Dense' object has no attribute 'kernel'

### ISSUE THREAD

**Issue by csyanbin** [siavash-khodadadeh/MetaLearning-TF2.0#2]
Hi, Siavash,

I am trying to run this code about umtra and maml, and get the following error:

```
No previous checkpoint found!
Traceback (most recent call last):
  File "models/maml/maml.py", line 495, in <module>
    run_mini_imagenet()
  File "models/maml/maml.py", line 490, in run_mini_imagenet
    maml.evaluate(50)
  File "models/maml/maml.py", line 277, in evaluate
    updated_model = self.inner_train_loop(train_ds, train_labels, iterations)
  File "models/maml/maml.py", line 226, in inner_train_loop
    self.create_meta_model(self.updated_models[0], self.model, gradients)
  File "models/maml/maml.py", line 142, in create_meta_model
    updated_model.layers[i].kernel = model.layers[i].kernel - self.lr_inner_ml * gradients[k]
AttributeError: 'Dense' object has no attribute 'kernel'
```

Do you know why this error would happen?

**Comment by csyanbin** [comment]
- [ ] Issue solved .
By commenting Line  60-61 in file networks.py
